targets:
  $default:
    builders:
      flamingo_generator|field_value_generator:
        generate_for:
          include:
            - lib/models/firebase/*.dart
            - lib/models/firebase/**/*.dart